<a href="https://colab.research.google.com/github/sdivyakolu/Pytorch_Tutorial/blob/main/PyTorch_DeepLearning1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
show_expected_result=True
show_hints=True

def find_latest(numbers):
  return max(numbers)


In [2]:
my_numbers=[4,-5,8,10,34]
result=find_latest(my_numbers)
result

34

In [5]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())



2.6.0+cu124
True


In [10]:
import torch

first_tensor=torch.tensor([[1,2,3,4],[5,6,7,8]])
second_tensor=torch.tensor([[11,12,13,14],[15,16,17,18]])
third_tensor=first_tensor+second_tensor
print(third_tensor)
print('Result Tensor Size:',third_tensor.size())

#Subtract tensor

subtract_tensor=first_tensor-second_tensor
print(subtract_tensor)
print('Subtract Result Tensor Size:',subtract_tensor.size())

#Multiply tensor

multiply_tensor=first_tensor*second_tensor
print(multiply_tensor)
print('Multiply Result Tensor Size:',multiply_tensor.size())

tensor([[12, 14, 16, 18],
        [20, 22, 24, 26]])
Result Tensor Size: torch.Size([2, 4])
tensor([[-10, -10, -10, -10],
        [-10, -10, -10, -10]])
Subtract Result Tensor Size: torch.Size([2, 4])
tensor([[ 11,  24,  39,  56],
        [ 75,  96, 119, 144]])
Multiply Result Tensor Size: torch.Size([2, 4])


In [14]:
import torch

print('Torch Version:' ,torch.__version__)
print('CUDA available:',torch.cuda.is_available())

if ( torch.cuda.is_available()): device=torch.device('cuda') #it will switch runtime to GPU
else : device=torch.device('cpu')

print('device:',device)


Torch Version: 2.6.0+cu124
CUDA available: True
device: cuda


In [16]:
first_tensor=torch.tensor([[1,2,3,4],[5,6,7,8]],device=device)
second_tensor=torch.tensor([[11,12,13,14],[15,16,17,18]],device=device)

multiply_tensor=first_tensor*second_tensor
multiply_tensor

tensor([[ 11,  24,  39,  56],
        [ 75,  96, 119, 144]], device='cuda:0')

In [1]:
import torch
import numpy as np

first_tensor=torch.tensor([1,2,3,4,5])
tuple_tensor=torch.tensor((5,6,7,8,9,0))

print('First Tensor:',first_tensor)
print('Tuble Tensor:',tuple_tensor)

#Initilizse tensor from numpyarray( nd_array)

tensor_from_array=torch.tensor(np.array([11,12,13,14,15]))

tensor_from_array

First Tensor: tensor([1, 2, 3, 4, 5])
Tuble Tensor: tensor([5, 6, 7, 8, 9, 0])


tensor([11, 12, 13, 14, 15])

In [8]:
#Practice torch.empty, torch.one, torch.zero

empty_tensor=torch.empty(3,4)
print('empty_tensor:',empty_tensor)

one_tensor=torch.ones(3,4)
print('One_tensor:', one_tensor)

zero_tensor=torch.zeros(3,4)
print('Zero tensor:',zero_tensor)


empty_tensor: tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00]])
One_tensor: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Zero tensor: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [11]:

first_tensor=torch.rand(3,4)

print('First Tensor:', first_tensor)

second_tensor=torch.randn(3,4)

print('Second Tensor:',second_tensor)

third_tensor=torch.randint(5,30,(3,4))
print('Third tensor:',third_tensor)

First Tensor: tensor([[0.3180, 0.1546, 0.7852, 0.7900],
        [0.9600, 0.6132, 0.0482, 0.8956],
        [0.6968, 0.1900, 0.9608, 0.1718]])
Second Tensor: tensor([[-0.0995,  2.0835,  0.1776, -0.7479],
        [-0.7418,  1.3030,  1.4889, -1.0508],
        [-1.1823,  0.9258, -0.4438, -1.7860]])
Third tensor: tensor([[23, 29,  7,  6],
        [25, 14, 20, 25],
        [27, 26, 24, 25]])
