<a href="https://colab.research.google.com/github/sdivyakolu/Pytorch_Tutorial/blob/main/PyTorch_DeepLearning1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
show_expected_result=True
show_hints=True

def find_latest(numbers):
  return max(numbers)


In [ ]:
my_numbers=[4,-5,8,10,34]
result=find_latest(my_numbers)
result

34

In [ ]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())



2.6.0+cu124
True


In [ ]:
import torch

first_tensor=torch.tensor([[1,2,3,4],[5,6,7,8]])
second_tensor=torch.tensor([[11,12,13,14],[15,16,17,18]])
third_tensor=first_tensor+second_tensor
print(third_tensor)
print('Result Tensor Size:',third_tensor.size())

#Subtract tensor

subtract_tensor=first_tensor-second_tensor
print(subtract_tensor)
print('Subtract Result Tensor Size:',subtract_tensor.size())

#Multiply tensor

multiply_tensor=first_tensor*second_tensor
print(multiply_tensor)
print('Multiply Result Tensor Size:',multiply_tensor.size())

tensor([[12, 14, 16, 18],
        [20, 22, 24, 26]])
Result Tensor Size: torch.Size([2, 4])
tensor([[-10, -10, -10, -10],
        [-10, -10, -10, -10]])
Subtract Result Tensor Size: torch.Size([2, 4])
tensor([[ 11,  24,  39,  56],
        [ 75,  96, 119, 144]])
Multiply Result Tensor Size: torch.Size([2, 4])


In [ ]:
import torch

print('Torch Version:' ,torch.__version__)
print('CUDA available:',torch.cuda.is_available())

if ( torch.cuda.is_available()): device=torch.device('cuda') #it will switch runtime to GPU
else : device=torch.device('cpu')

print('device:',device)


Torch Version: 2.6.0+cu124
CUDA available: True
device: cuda


In [ ]:
first_tensor=torch.tensor([[1,2,3,4],[5,6,7,8]],device=device)
second_tensor=torch.tensor([[11,12,13,14],[15,16,17,18]],device=device)

multiply_tensor=first_tensor*second_tensor
multiply_tensor

tensor([[ 11,  24,  39,  56],
        [ 75,  96, 119, 144]], device='cuda:0')

In [ ]:
import torch
import numpy as np

first_tensor=torch.tensor([1,2,3,4,5])
tuple_tensor=torch.tensor((5,6,7,8,9,0))

print('First Tensor:',first_tensor)
print('Tuble Tensor:',tuple_tensor)

#Initilizse tensor from numpyarray( nd_array)

tensor_from_array=torch.tensor(np.array([11,12,13,14,15]))

tensor_from_array

First Tensor: tensor([1, 2, 3, 4, 5])
Tuble Tensor: tensor([5, 6, 7, 8, 9, 0])


tensor([11, 12, 13, 14, 15])

In [ ]:
#Practice torch.empty, torch.one, torch.zero

empty_tensor=torch.empty(3,4)
print('empty_tensor:',empty_tensor)

one_tensor=torch.ones(3,4)
print('One_tensor:', one_tensor)

zero_tensor=torch.zeros(3,4)
print('Zero tensor:',zero_tensor)


empty_tensor: tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00]])
One_tensor: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Zero tensor: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:

first_tensor=torch.rand(3,4)

print('First Tensor:', first_tensor)

second_tensor=torch.randn(3,4)

print('Second Tensor:',second_tensor)

third_tensor=torch.randint(5,30,(3,4))
print('Third tensor:',third_tensor)

First Tensor: tensor([[0.1358, 0.6168, 0.0987, 0.3678],
        [0.1181, 0.9442, 0.4116, 0.9849],
        [0.9826, 0.1287, 0.9857, 0.1848]])
Second Tensor: tensor([[-0.1527,  0.7351,  0.6345, -1.1348],
        [ 0.5021,  1.5000,  1.4382,  2.0083],
        [-1.6319, -0.8848, -3.2420,  0.0226]])
Third tensor: tensor([[27, 18, 27, 27],
        [21, 29,  7, 16],
        [19,  9, 16, 25]])


In [ ]:
import torch
onelike_tesor=torch.ones_like(third_tensor)
onelike_tesor

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [ ]:
### Exercise 2 dimensional tensor from paython list
python_list=[[1,2,3,4],[5,6,7,8]]
tensor_from_array=torch.tensor(python_list)
print("tensor_from_array:",tensor_from_array)

###Excercise 2 dimensional tensor from numpy array

import numpy as np

numpy_array=np.array([[1,2,3,4],[5,6,7,8]])

tensor_from_numpy_array= torch.tensor(numpy_array)
print("tensor_from_numpy_array:", tensor_from_numpy_array)


tensor_from_array: tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor_from_numpy_array: tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [ ]:
def create_tensor_ones(rows,columns):
    # Your code goes here
    tensor_ones=torch.ones(rows,columns)
    return tensor_ones



In [ ]:
  new_one_tensor=create_tensor_ones(3,4)
  print(new_one_tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
#Create tensor of shape 4x5 and fill data with value of 5
def create_customize_tensor(rows,columns,value):
  tensor_customize=torch.full((rows,columns),value)

  return tensor_customize


In [ ]:
  customize_tensor=create_customize_tensor(3,4,5)
  print(customize_tensor)
  torch.full

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])


<function torch._VariableFunctionsClass.full>

In [ ]:
import torch

chapter4_tensor=torch.tensor([1,2,3,4,15,6,7,8])
print(chapter4_tensor)
print('4th Item:',chapter4_tensor[4])
print('4th Element value:',chapter4_tensor[4].item())

print('SubElements:',chapter4_tensor[2:6])

tensor([ 1,  2,  3,  4, 15,  6,  7,  8])
4th Item: tensor(15)
4th Element value: 15
SubElements: tensor([ 3,  4, 15,  6])


In [ ]:
two_dimension_tensor=torch.tensor([[1,2,3,4,5,6],[11,12,13,14,15,16],[21,22,23,24,25,26],[31,32,33,34,35,36]])
two_dimension_tensor[0][2]

tensor(3)

In [ ]:
print(two_dimension_tensor[0,2:4])
print(two_dimension_tensor[1,2:4])

tensor([3, 4])
tensor([13, 14])


In [ ]:
two_dimension_tensor[two_dimension_tensor <=4]

tensor([1, 2, 3, 4])

In [ ]:
import torch

torch.stack((two_dimension_tensor,two_dimension_tensor))
two_dimension_tensor

tensor([[ 1,  2,  3,  4,  5,  6],
        [11, 12, 13, 14, 15, 16]])

In [ ]:
import torch
first_tensor,second_tensor,third_tensor,forth_tensor=torch.unbind(two_dimension_tensor)
first_tensor,second_tensor,third_tensor,forth_tensor

(tensor([1, 2, 3, 4, 5, 6]),
 tensor([11, 12, 13, 14, 15, 16]),
 tensor([21, 22, 23, 24, 25, 26]),
 tensor([31, 32, 33, 34, 35, 36]))

In [ ]:
import torch
a=torch.tensor([1,2,3,4,5])
b=torch.tensor([11,12,13,14,15])
c=a.add(b)
print('Add-Output:',c)
d=a.min(b)
print('Min-Output:',d)
d1=a.max(b)
print('Max-Output:',d1)
e=a.mul(b)
print('Multiply-Output:',e)

Add-Output: tensor([12, 14, 16, 18, 20])
Min-Output: tensor([1, 2, 3, 4, 5])
Max-Output: tensor([11, 12, 13, 14, 15])
Multiply-Output: tensor([11, 24, 39, 56, 75])


In [ ]:
#Reduction Functions
#Mean , median,mode , average , std

a=torch.tensor([1.,2.,3.,4.,5.,6.,7.,8.,9.])

meanVal=a.mean()
print('Mean Val:',meanVal)

median=a.median()
print('Median Val:',median)

mode=a.mode()
print('Mode:',mode)

Mean Val: tensor(5.)
Median Val: tensor(5.)
Mode: torch.return_types.mode(
values=tensor(1.),
indices=tensor(0))


In [3]:
import torch

matrix1=torch.tensor([1,2,3,4,5,6,7])
matrix2=torch.tensor([11,12,13,14,15,16,17])

resultMatrix=torch.matmul(matrix1,matrix2);
print(resultMatrix)

tensor(420)


In [7]:
import torch

matrix1=torch.tensor([[1,2,3],[-1,-2,-3]])
matrix2=torch.tensor([[11,12],[-11,-12],[22,32]])

resultMatrix=torch.matmul(matrix1,matrix2);
print(resultMatrix)

tensor([[ 55,  84],
        [-55, -84]])


In [8]:
import torch

matrix1=torch.randn(2,3)
matrix2=torch.randn(3,4)
matrix3=torch.randn(4,5)
matrix4=torch.randn(5,6)

resultMatrix=torch.linalg.multi_dot([matrix1,matrix2,matrix3,matrix4])
print(resultMatrix)

tensor([[  0.6390,   4.3741,   0.6536,  -1.3411,   1.5425,  -0.6177],
        [ -1.2060,  -7.5110,  -0.5975,   5.3018, -13.0238,   4.9166]])


In [9]:
#Print Egan values
import torch

matrix1=torch.randn(3,3)

resultMatrix=torch.linalg.eig(matrix1)

print(resultMatrix)


torch.return_types.linalg_eig(
eigenvalues=tensor([-0.0102+1.6092j, -0.0102-1.6092j,  0.0461+0.0000j]),
eigenvectors=tensor([[ 0.2536+0.5619j,  0.2536-0.5619j, -0.2737+0.0000j],
        [ 0.3382+0.1537j,  0.3382-0.1537j,  0.5884+0.0000j],
        [-0.6943+0.0000j, -0.6943-0.0000j,  0.7608+0.0000j]]))


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
