<a href="https://colab.research.google.com/github/sdivyakolu/Pytorch_Tutorial/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [3]:
tensor_a=torch.tensor([1,2,3,45])
tensor_b=torch.tensor([0,9,8,7])


In [4]:
#additions
tensor_a+tensor_b

tensor([ 1, 11, 11, 52])

In [5]:
#Addition Longhand
torch.add(tensor_a,tensor_b)


tensor([ 1, 11, 11, 52])

In [6]:
#Subtraction
tensor_a-tensor_b

tensor([ 1, -7, -5, 38])

In [8]:
#Subtraction longhand
torch.subtract(tensor_a,tensor_b)

tensor([ 1, -7, -5, 38])

In [9]:
#Multiplication
tensor_a*tensor_b

tensor([  0,  18,  24, 315])

In [10]:
#Multiplication from torch
torch.multiply(tensor_a,tensor_b)

tensor([  0,  18,  24, 315])

In [12]:
#remainder
tensor_b%tensor_a

tensor([0, 1, 2, 7])

In [13]:
#Remainder long hand
torch.remainder(tensor_b,tensor_a)

tensor([0, 1, 2, 7])

In [14]:
#Exponents
torch.pow(tensor_a,tensor_b)

tensor([           1,          512,         6561, 373669453125])

In [15]:
#another way to write longband
tensor_a.add(tensor_b)

tensor([ 1, 11, 11, 52])

In [18]:
#Reassignment
tensor_b=tensor_b + tensor_a
tensor_b

tensor([  3,  15,  17, 142])

In [19]:
#tensor_a = tensor_a + tensor_b ( with reassignment)
tensor_a.add_(tensor_b)
tensor_a

tensor([  4,  17,  20, 187])