<a href="https://colab.research.google.com/github/sdivyakolu/Pytorch_Tutorial/blob/main/Tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_torch=torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#Reshaoe and view
my_torch=my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [23]:
#reshape if we don't know the number of items using -1
my_torch2=torch.arange(18)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [26]:
my_torch2=my_torch2.reshape(2,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [28]:
my_torch3=torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
my_torch4=my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [30]:
#Difference between shape and view
#Go and figure out yourself
#With reshape and view , they will update
my_torch5=torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
my_torch6=my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [32]:
my_torch5[1]=4123
my_torch5

tensor([   0, 4123,    2,    3,    4,    5,    6,    7,    8,    9])

In [33]:
my_torch6

tensor([[   0, 4123,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [35]:
#Slice
my_torch7=torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
#grab a specifc item based on index
my_torch7[7]

tensor(7)

In [39]:
#Grab slice
my_torch8=my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [49]:
my_torch8[:,0]

tensor([0, 2, 4, 6, 8])

In [41]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [45]:
my_torch8[0,:]

tensor([0, 1])